### ISSUE TITLE
error vcenter_server

### ISSUE THREAD

**Issue by eunicebello7** [www-aiqu-no/terraform-vsphere-linux-vm#1]
Hi, 

I'm new at this, so maybe I'm doing something wrong. But after I configure all parameters, it gives me this error:

_Error: one of vsphere_server or [deprecated] vcenter_server must be provided

  on <input-prompt> line 1:
  (source code not available)_

But during the config it never asks for a vcenter_server value, so where am I suppose to set it?

**Comment by runeron** [comment]
Sorry for not replying. Assuming it's too late for you, but adding reply in case anyone else has the same problem.

You need to add the provider:
https://www.terraform.io/docs/providers/vsphere/index.html
